civisanalytics/civis-python

docs/source/index.rst
The repository name is incorrect, methinks.
=> Updates documentation: s/civis-client/civis-python

civis/cli/__main__.py, civis/tests/test_polling.py, civis/tests/testcase.py, requirements.txt
We don't need to pin to specific minor and micro versions of `requests` and `pyyaml`. Tell pip that it's okay to have newer versions of those libraries with the same major version.
=> MAINT Be less strict with requirements

README.md, docs/source/conf.py
This will ensure the local documentation generated includes all the resources the current user has access to
=> Use 'all' resources when generating local docs

dev-requirements.txt, docs/source/user_guide.rst
Found a small error in the user_guide documentation.  This fixes that error.
In the process of this PR, a new version of `flake8` came out which caused the code to fail tests.  Those changes were addressed in #3.  However, that prompted me to pin the versions of dev requirements (which is also included in this PR).
=> fixing a small typo in the user_guide

civis/io/_tables.py
`drop` is an option in `client.imports.post_files` but wasn't explicitly listed in `dataframe_to_civis` or `csv_to_civis`.  This adds that documentation.
=> Adding "drop" option in docs for table uploads

civis/base.py, civis/response.py, civis/tests/test_response.py
If a 204/205 response is returned from the API, and the client is set to the default return type of `'snake'`, an exception would be thrown.
This PR returns a valid civis.response.Response object from these responses.  The `json_data` attribute is set to `None` to disambiguate empty JSON responses from no content responses.
An alternative is to propagate the `None` value back to the user, instead of returning a `Response` object.  This is significantly easier, but loses the response headers.  I'm not opposed to switching to that approach if we think it would be better.
=> Return a valid Response object on None responses

.gitignore, CHANGELOG.md, civis/io/_databases.py, civis/io/_tables.py
For the `civis.io` functions, change the `archive` parameter (this ran a callback which archived the script after completion) to `hidden`. Instead of archiving scripts when they finish, hide them on creation. This is what the `archive` parameter had been trying to accomplish. Setting `hidden` keeps the scripts from cluttering the UI while leaving them accessible to e.g. status queries from the API. We also save the latency of an extra API call on script completion.
This PR also adds the `hidden` option to the `query_civis` function, which didn't have it before.
=> ENH Switch "archive" to "hidden"

CHANGELOG.md, civis/resources/_resources.py
The API endpoints returned by the Platform were already being cached, but parsing the results of this call takes > 0.5 seconds. Caching the result of the entire swagger-parsing process is memory-cheap and gives a 1000x decrease in time required to create identical client objects. Creation is now ~150 us, fast enough that we can re-create client objects as needed with no performance overhead.
=> [CIVP-10002] Cache swagger generation

civis/civis.py
The GET `/credentials` endpoint is now paginated. So it is possible your default credential is not in the first page of results when doing a GET on `/credential`s. However, there is a request param you can use to ensure you get the default credential so we should use that in the `default_credential` helper method.
=> [CIVP-9993] Default Credential: use default=true option in LIST request

docs/source/index.rst
Without the `export ` it doesn't work.  John Means and @dianecarroll encountered this difficulty when trying to set up from docs.
=> Update documentation: docs/index

civis/resources/_resources.py, civis/tests/test_resources.py
An HTTP 401 error raises when a user tries to use the client when their API key is expired.  This makes the error a little more clear.
=> [CIVP-10035] Adding helpful error for 401s when API key is expired

civis/resources/_resources.py
The url for fetching the swagger was harcoded in `civis/resources/_resources.py`. Using `Endpoint._base_url` in case the url ever changes we only need to update it in one place.
=> Use Endpoint._base_url when fetching swagger

civis/pubnub.py
I think when I initially built this, I was looking at documentation on an older Pubnub SDK when adding in the reconnection policy. This PR should fix the reconnection policy based on SDK v4.
=> Fixed reconnection policy for pubnub connections

civis/tests/test_client.py, civis/tests/test_io.py, civis/tests/test_pubnub.py
There was a transient test failure where the `get_swagger_spec` and `generate_classes` functions would not use the expected swagger mock. In the tests, there are 2 swagger specs: one is the base spec, the other is the base + channels. Different test files will mock different swagger specs, but since the `get_swagger_spec` and `generate_classes` functions use an LRU cache, the cached value would persist between tests which would cause a failure on Pubnub tests when the base swagger spec is cached.
The fix for this is clearing the LRU cache on these functions on setup and tear down of the classes that mock the swagger spec.
=> Clear LRU cache on test cases that mock swagger spec

civis/resources/_resources.py, civis/tests/test_resources.py
Currently, API resource methods take optional parameters in the form of `**kwargs` in the method signature.  This is convenient for parsing the API specification, but can produce unexpected behavior when an unexpected keyword argument is passed into the method.  Instead of alerting the user that the argument is unexpected, it is simply ignored (causing some confusion).  This change adds an explicit check on all method calls for unexpected arguments so that they may be caught earlier.
=> [CIVP-10066] Catch unexpected keyword arguments passed to methods

CHANGELOG.md, README.md, civis/io/_files.py
If users have `requests-toolbelt` installed, then we can stream files into AWS without needing to read them into memory all at once. This allows users to upload files larger than they could have otherwise (e.g. tens of GB).
=> ENH Use requests-toolbelt for streaming uploads of Files

.travis.yml
Moved from https://github.com/civisanalytics/civis-python/pull/34.  This relaxes our tests so that warnings from `sphinx_build` don't raise errors in Travis.  This is a work around to avoid non-deterministic network errors in the sphinx build.  An alternative approach would be to cache external doc resources in the repo and increase the complexity of docs, which seems to me to be worse than slightly relaxing our tests for doc building.
=> Allow tests to pass with warning in sphinx build

CHANGELOG.md, README.md, civis/base.py, civis/futures.py, civis/io/_databases.py, civis/io/_tables.py, docs/source/user_guide.rst
Now that the `futures.CivisFuture` class exists, replace all uses of `PollableResult` with `CivisFuture`. This improves performance by increasing speed (we find out that runs complete immediately, instead of after polling) and by reducing the number of API calls needed.
=> [CIVP-10187] Replace PollableResult with CivisFuture

civis/futures.py, civis/polling.py
There were a couple of circumstances where exceptions raised in polling could have left us still subscribed to the `pubnub` notifications channel. Refactor the exception setting so that it only happens in one place; that way we can be sure that `cleanup` always gets called.
After this change, there's now only one place where we call `set_exception`, just as there's only one place where we call `set_result`.
=> BUG Make sure that the CivisFuture always cleans up after exceptions

civis/base.py, civis/resources/_resources.py, civis/tests/test_base.py
Allow the base url of the API to be configured through the `CIVIS_API_ENDPOINT` environment variable.
=> [CIVP-10381] Allow base url to be configured from environment variable

CHANGELOG.md, civis/resources/_resources.py
This retries the call to `/endpoints` while instantiating the client for certain errors.   Another possible route might be to pass the `_session` object from `APIClient`, but this would prevent us from being able to memoize `generate_classes`.
=> [CIVP-10635] Adding retries during the call to /endpoints in get_swagger_spec

CHANGELOG.md, README.md, civis/base.py, civis/civis.py, civis/resources/_resources.py, civis/tests/test_polling.py, requirements.txt
If we have a rate limit error (429) and a Retry-After header, it should always be safe to retry the request, regardless of the verb. The `Retry.is_retry` method starts by checking if the verb is on the whitelist (defaults to ['HEAD', 'GET', 'PUT', 'DELETE', 'OPTIONS', 'TRACE']) and immediately returns False if it is not. This PR changes our code so that we will retry on the `RETRY_AFTER_STATUS_CODES` ([413, 429, 503]) regardless of verb.
See https://github.com/shazow/urllib3/blob/50705abd83be4ad7997eeefe9e732564af1db118/urllib3/util/retry.py#L285L299 .
`urllib3` respects the "Retry-After" header starting at v1.19. We get `urllib3` from `requests`; `requests` updated `urllib3` to a compatible version at v2.12.0. Therefore this PR also needs to increase the version of `requests` which we …
=> [CIVP-10208] Retry all HTTP verbs with a Retry-After header and an approved error

civis/futures.py, docs/source/responses.rst
Replace `PollableResult` with `CivisFuture` in the sphinx documentation.
=> DOC Add `CivisFuture` to docs, remove `PollableResult`

CHANGELOG.md, civis/io/_files.py
We can't upload files larger than 5GB to s3. Also, AWS provides more informative errors than what requests will raise by default.
=> [CIVP-10864] ENH: Error on file too large.

CHANGELOG.md, civis/resources/_resources.py, civis/tests/test_client.py, civis/tests/test_futures.py, civis/tests/test_io.py, civis/tests/test_resources.py, docs/source/conf.py
The Swagger Specification has been renamed to OpenAPI Specification.  This PR removes references of "swagger" to make the code more clear.
=> REF: Refactoring out use of 'swagger'

CHANGELOG.md, civis/civis.py, civis/resources/__init__.py, civis/resources/_resources.py, civis/tests/test_resources.py, docs/source/client.rst
This PR adds the parameter `local_api_spec` to `APIClient` to allow users to create a client object from a local cache of the Civis API specification.  This parameter can be either an OrderedDict or a string which points to a file of the specification (parsing expects an order to the specification, hence why a regular dict cannot be used).
I'm also exposing `get_swagger_spec` in `civis.resources` as the intended workflow is to call `get_swagger_spec` to download the specification for caching.
=> [CIVP-10867] Use cache to create APIClient

CHANGELOG.md, civis/io/_tables.py
Clarify that the index is not stored, and point users to `reset_index`.
Closes #61 .
=> DOC Add note about index to dataframe_to_civis

CHANGELOG.md, civis/futures.py, civis/polling.py, civis/tests/test_futures.py, civis/tests/test_polling.py
* Added `_reset_polling_thread` to `PollableResult` which stops the current polling thread and creates a new one with the specified polling interval (defaults to the default interval of 15)
* Added a status handler in the PubNub listener class which will check if the status matches a set of statuses that pertain to unexpected disconnects or network errors and call the `_reset_polling_thread` function if it is disconnected.
=> [CIVP-10738] Poll on a lower interval when PubNub fails

docs/source/conf.py
Sphinx's `make html` was failing for me, and I think it's because `user_agent` is no longer an argument for `generate_classes`.
=> BUG remove argument that prevents sphinx from building docs

CHANGELOG.md, civis/io/__init__.py, civis/io/_files.py, civis/io/_tables.py, civis/tests/test_io.py
Add the functions `civis.io._files.file_id_from_run_output`, `civis.io._files.file_to_dataframe`, and `civis.io._files.file_to_json`. These functions will be used for the forthcoming modeling interface code, but are also of general interest.
=> [CIVP-10806] Add more utility functions for working with Civis files

civis/ml/__init__.py, civis/ml/_model.py, civis/ml/tests/test_model.py
This is the next step in adding the new modeling interface. This PR adds the new `civis.ml` namespace, and populates it with `ModelFuture`, a subclass of `CivisFuture`. The `ModelFuture` object knows how to find and download results from a CivisML model. It also transports errors from Civis and re-raises them in the local environment to make debugging easier.
=> [CIVP-10806] Add ModelFuture

civis/ml/_model.py, civis/ml/tests/test_model.py
Use a keyword argument for `client`, since the fourth positional argument is `regex`. The new test fails with this error in place.
=> [CIVP-10806] BUG Fix parameter bug in _load_table_from_outputs

civis/ml/_model.py, civis/ml/tests/test_model.py
Training jobs with older templates should use prediction jobs whose templates match the version of the training job. This is to ensure that the prediction job is getting exactly the metadata it expects, and has exactly the correct versions of all dependencies.
=> [CIVP-10806] ENH ModelPipeline.from_existing select best prediction template

civis/ml/_model.py, civis/ml/tests/test_model.py
The `ModelFuture` takes a train job ID as the third positional argument, not the client. Pass the client as a keyword argument instead.
=> [CIVP-10806] BUG Give client as keyword argument for ModelFuture

civis/ml/_model.py, docs/source/conf.py, docs/source/index.rst, docs/source/ml.rst
This adds Sphinx documentation for the new `civis.ml` namespace. This PR includes changes to the doc strings in `civis.ml` to make the formatting nicer on the autodoc'ed Sphinx page.
=> [CIVP-10806] DOC Documentation for civis.ml namespace

.travis.yml, civis/ml/_model.py, civis/ml/tests/test_model.py
We had been using the associated job and run IDs, when we should have been using the job and run IDs of the connected training job.
=> [CIVP-11088] Use correct job/run ID when fetching training metadata

civis/tests/test_polling.py
This was causing failures in https://github.com/civisanalytics/civis-python/pull/77.
=> [CIVP-11102] TST remove non-deterministic polling test

civis/ml/_model.py
Older model templates used "WORKFLOW" where the new templates have "MODEL". When loading an old model, check first for "MODEL" and next for "WORKFLOW". It will have one of these if it's a CivisML job.
=> [CIVP-10806] BUG Allow `from_existing` to handle v0 templates

civis/ml/_model.py, civis/ml/tests/test_model.py
Modify the `ModelFuture` to notice when the jobs it's connected to failed because they ran out of memory. If that happened, re-raise an appropriate error so that the user can handle it. We can't do anything about this on the Platform side -- Python dies abruptly without being able to write any outputs.
Before:
After:
=> [CIVP-11103] ENH ModelFuture recognize and raies MemoryErrors

civis/ml/tests/test_model.py
PR #79 added test code in the `test_model` module which is not Python 2-compatible. This fixes it.
=> [CIVP-11103] COMPAT Fix test in test_model for Python 2

civis/ml/_model.py
The v0 CivisML templates used a different format for database arguments. Check the template ID, and use the appropriate format. This will let users with models trained under v0.5 continue to run prediction jobs.
=> [CIVP-11386] COMPAT Make ModelPipeline DB args v0 compatible

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
There are integer-like types, such as `numpy.int64`, which can't be JSON-serialized by default. This causes errors when we need to JSON-serialize parameters to the templates. Force all of the integer arguments to Python integers.
=> [CIVP-11376] BUG ModelPipeline handles np.int64 integer arguments

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
In #79, the entire `if` gate in `ModelPipeline._set_model_exception` was removed, when I should only have removed the part after the `and`. If we don't have the `if an exception happened in the job` check, we'll set an exception on all `ModelFuture` objects, even if everything succeeded.
=> [CIVP-11393] BUG Only set exceptions on ModelFuture if there was an error

civis/ml/tests/test_model.py
Dictionaries are not guaranteed to have any order, and in particular, the order may change between Python versions. Test both possible orderings.
=> TST Fix test which relied on dictionary order

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
This was the only `@property` that wasn't tying the file ID lookups to the training job.
EDIT: now pointing at `release-1.5`.
=> [CIVP-11423] BUG get validation metadata from training job for prediction future

CHANGELOG.md, civis/futures.py, civis/ml/_model.py, civis/polling.py
We have at least once instance of a bug which looks to be caused by non-threadsafe code. The most likely culprit is in the `PollableResult` stack. Add some extra locks to avoid possibly double-destroying anything. `cleanup` looks like it was always called from inside a function holding the lock, so it's probably fine. It doesn't hurt to add an extra lock. `_reset_polling_thread` wasn't behind a lock, and it was being used as a callback from `pubnub` -- perhaps this could have been a problem?
=> [CIVP-11427] BUG Improve thread safety in PollableResult

CHANGELOG.md, requirements.txt, setup.py
Hopefully fixes the following error on Python 3, but I haven't been able to replicate not installing from PyPI.
```
Using cached functools32-3.2.3-2.zip
Complete output from command python setup.py egg_info:
This backport is for Python 2.7 only.
```
Issue is described in the following
https://github.com/inveniosoftware/invenio-oaiserver/issues/112
https://github.com/Julian/jsonschema/issues/228
https://hynek.me/articles/conditional-python-dependencies/
https://wheel.readthedocs.io/en/latest/#defining-conditional-dependencies
And the differing usage of install_requires vs requirements.txt here
https://packaging.python.org/requirements/
=> [CIVP-11405] BLD: Fix functools32 installation

MANIFEST.in
I missed this when converting the readme from Markdown to reStructuredText at #83. Probably no bugfix release is needed.
=> [CIVP-11087] Fix readme filename extension in MANIFEST.in

civis/futures.py, civis/ml/_model.py, civis/tests/test_futures.py
Add a `ContainerFuture` object which knows how to query container scripts, how to cancel container scripts, and how to retry container scripts. The `civis.ml.ModelFuture` can be a subclass of the `ContainerFuture`; models are a specialized container script.
This functionality (especially retries) adds more tooling for running concurrent jobs on the Civis Platform, and is a setup for executor classes coming in the next PR.
=> [CIVP-11787] ENH ContainerFuture class to track container scripts

civis/futures.py, civis/tests/test_futures.py
Add two Civis-specific Executor classes (subclasses of the standard library `concurrent.futures.Executor`). The `_ContainerShellExecutor` uses Civis Platform container jobs to parallelize over either shell commands or container script arguments. The `CustomScriptExecutor` parallelizes over arguments to a custom script.
=> [CIVP-11787] ENH futures.Executor classes for Civis

civis/cli/__main__.py
The CLI didn't indicate the types of required arguments, and this was confusing for cases like `civis scripts put-containers-archive`, where a "status" boolean is expected.
Note that YAML is 
Before:
```
» civis scripts put-containers-archive --help
Usage: civis scripts put-containers-archive [OPTIONS] ID STATUS
Update the archive status of this object
/scripts/containers/{id}/archive
ID - The ID of the object.
STATUS - The desired archived status of the object.
...
```
After:
```
» civis scripts put-containers-archive --help
Usage: civis scripts put-containers-archive [OPTIONS] ID STATUS
Update the archive status of this object
/scripts/containers/{id}/archive
ID (integer) - The ID of the object.
STATUS (boolean) - The desired archived status of the object.
...
```
Note that yaml is …
=> show expected types of arguments in the CLI

CHANGELOG.md, civis/compat.py, civis/parallel.py, civis/run_joblib_func.py, civis/tests/test_parallel.py, dev-requirements.txt, setup.py
Add a new `civis.parallel` module which contains tools to register a custom backend for the `joblib` library. This will let users leverage the Civis Platform infrastructure for parallel computing, and makes it easy to distribute parallel scikit-learn computations over the Civis infrastructure.
Most of this code was developed in a separate repo and has been in Civis internal use. This PR copies over that code, adapts it to work in the civis-python repo, and makes small modifications for Python 2 compatibility.
=> [CIVP-11787] Add joblib backend

civis/run_joblib_func.py
In the joblib backend remote runner script, the `joblib.load` call will fail if we try to load an object which refers to code that's not in our remote environment. That's an easy mistake to make, and we should make sure that users see an informative error from it. By moving the `load` call inside the try/finally block, we can record any exceptions from the `load` call and pass them back to the parent process.
=> BUG Include joblib.load in wrapper function error handling

.travis.yml, CHANGELOG.md, civis/futures.py, civis/ml/_model.py, civis/ml/tests/test_model.py, civis/parallel.py, civis/tests/test_futures.py, dev-requirements.txt, docs/source/index.rst, docs/source/ml.rst, requirements.txt, setup.py
Both the `joblib` and `pubnub` external libraries provide valuable functionality for users of the Python API client, and they are light, fast to install packages. Make them hard dependencies. Remove code paths which allowed those libraries to be absent, and modify the documentation to reflect the fact that all users will have those two libraries installed.
=> [CIVP-12032] DEP Make joblib and pubnub hard dependencies

civis/futures.py, civis/parallel.py, civis/tests/test_parallel.py
Allow users to pass keyword arguments to ``_ContainerShellExecutor`` and ``make_backend_factory`` and ``infer_backend_factory``. These keyword arguments will be passed directly to ``APIClient.scripts.post_containers``. An example of a new argument which users might want to pass is "cancel_timeout".
There's no modification to the changelog since this PR changes only unreleased code.
Closes #108 .
TODO
=> [CIVP-12028] ENH Allow arbitrary keyword arguments to joblib backend

civis/parallel.py, civis/run_joblib_func.py
Large-scale jobs sometimes encounter 500 errors from web communications with S3. We can greatly reduce the chance of these failures interrupting a job by retrying ``file_to_civis`` and ``civis_to_file`` operations.
Add a wrapper for ``civis.io.file_to_civis`` which retries on network errors. Rename ``_robust_result_download`` to ``_robust_pickle_download``, since we don't care that the contents of the file are a result. Use these functions for upload and download on both sides of the joblib backend.
There's no new changelog entry because this PR modifies unreleased code.
Closes #109 .
=> [CIVP-12029] ENH Retry uploads and downloads in joblib backend

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
If a modelling job is cancelled, then `fut.metadata` raises a `concurrent.future.CancelledError`. The `ModelFuture._set_model_exception` callback needs to allow for this -- if the job is cancelled, there's no new error to set, and we don't want to raise anything.
=> [CIVP-12088] BUG Stop ModelFuture cancellation error

civis/parallel.py, docs/source/conf.py, docs/source/index.rst, docs/source/parallel.rst
Add RST documentation about how to use the new joblib backend. Includes some tweaks to docstrings for better formatting in web documentation.
=> [CIVP-11787] DOC Document use of joblib backend

CHANGELOG.md, civis/cli/__main__.py
The comment in the code indicates that the cache should last 24 hours. The 10 second expiration is likely a holdover from debugging.
=> [CIVP-12119] BUG Expire the CLI's API spec cache after 24 hours

CHANGELOG.md, civis/parallel.py, civis/run_joblib_func.py, docs/source/parallel.rst, requirements.txt, setup.py
Switch from serializing with `joblib` to using `cloudpickle`. `joblib` is more efficient than pickle protocol 2 for storing numpy arrays, but pickle protocols 3 and 4 (available in Python 3) are just as good as `joblib` for array data. `cloudpickle` adds the ability to transport dynamically defined functions and classes, so that users don't need to create installable Python modules to run a single custom function in the Civis Platform.
Using protocol `pickle.HIGHEST_PROTOCOL` guarantees that we get the best protocol for our version of Python. This does assume that users have the same Python version on both ends of the `joblib.Parallel` call.
TODO:
=> [CIVP-12068] ENH Serialize with cloudpickle

.travis.yml, CHANGELOG.md, civis/ml/tests/test_model.py, dev-requirements.txt, setup.cfg
`pandas` and `scikit-learn` are optional dependencies for the Python API client. We have tests which exercise these code paths, but the libraries aren't installed in the Travis testing environment, so we don't test the functions. This adds `pandas` and `sklearn` to Travis so that we're no longer skipping tests.
Increase the required version of `vcrpy`; previously the `civis/tests/test_io.py::ImportTests.test_read_civis_pandas` test would error on Python 3.6 with
`TypeError: request() got an unexpected keyword argument 'encode_chunked'`. This was a `vcrpy` Python 3.6 incompatibility, fixed in their v1.11 release.
Also tweak the tests in test_model.py so that we're not raising uncaught warnings.
After this PR, no tests are skipped, and the test suite doesn't raise any warnings.
=> [CIVP-12117] TST Run pandas and scikit-learn tests in Travis

CHANGELOG.md, civis/_utils.py, civis/base.py, civis/civis.py, civis/cli/__main__.py, civis/resources/_resources.py, civis/tests/test_cli.py
When retrieving the API spec in the Civis client CLI, use the same code as we use in the client library. This has the advantage of including automatic retries for connection failures, and automatic waiting for rate limit refreshes. Also modify `invoke` so that we include the same retries as we would if we were using the client library.
Includes a refactor to move all of our connection setup logic to the same place.
The CLI will now use a User-Agent string which starts with "civis-cli" so that we can distinguish it from the Python client.
=> [CIVP-10885] ENH Retry connection errors in CLI

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
This PR fixes a bug where instantiating a `ModelPipeline` instance from a CivisML model run with a templated script fails due to improper defaults for the `PARAMS` and `CVPARAMS` keys.
=> [CIVP-12351] BUG make sure to pass proper defaults for PARAMS and CVPARAMS

docs/source/conf.py
Use the `object_pairs_hook` kwarg to ensure that parameters show up in the right order in the Sphinx docs.
=> [CIVP-11612] Fix param order in generated docs

CHANGELOG.md, civis/__init__.py
The `ml` and `parallel` namespaces weren't part of `civis.__init__.py`'s `__all__`, so users needed to use e.g. `from civis.ml import ModelPipeline` instead of `civis.ml.ModelPipeline`. This change makes `ml` and `parallel` part of the top-level namespace.
=> BUG Add ml and parallel to civis namespace

civis/ml/_model.py, civis/ml/tests/test_model.py
Currently, multi-indexed dataframes get read in, and the job fails down the line, throwing an uninformative error. This PR checks for multi-indexed dataframes directly, and throws an informative error to let the user know they are not supported.
=> [PARO-436] BUG raise more informative error when multi-indexed dataframe is passed in

CHANGELOG.md, civis/response.py, civis/tests/test_response.py
The `PaginatedResponse` provided iteration support, but didn't implement the `__next__` method. This meant that the object itself was not an iterator. A small tweak can turn it into an iterator itself. Since the `PaginatedResponse` is returned when users provide an `iterator=True` argument to list endpoints, it seems reasonable for them to expect the returned object is an iterator.
=> BUG Fully implement iterator protocol in PaginatedResponse

CHANGELOG.md, civis/io/_tables.py
The `_download_callback` used by `civis.io.civis_to_csv` assumed that the future it's attached to returned some output. If that weren't the case (either the query errored or succeeded with no results), then the user would see an `IndexError` display on the screen, but not halt program execution. This is confusing. Intercept the error and replace it with a warning.
=> BUG Avoid IndexError on empty civis_to_csv queries

CHANGELOG.md, civis/io/_tables.py, dev-requirements.txt
This PR updates the docstring of `civis.io.civis_to_multifile_csv` by fixing the example code snippet as well as providing more details on the return dict. The updated docstring for the return dict looks like the following in the compiled Sphinx docs:
Also, while I was compiling the Sphinx docs locally to verify the changes, it's occurred to me that the packages `sphinx_rtd_theme` and `numpydoc` are needed, and so I've added them to `dev-requirements.txt`.
=> [CIVP-12579] Update docstring of "civis_to_multifile_csv"

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
If users called `ModelPipeline.from_existing` on a model training job which used a version of CivisML newer than what the client is aware of, we got errors because the prediction template ID was set to `None`. Let's warn and default to the newest known prediction template. At the very least, this should generate much clearer errors when the prediction job does a version check.
=> BUG ModelPipeline.from_existing handle future training templates

CHANGELOG.md, civis/resources/_resources.py, civis/tests/test_resources.py
Previously, optional arguments were all absorbed in a `**kwargs` blob and pulled out later. This changes to set all of them explicitly in the function signature. Doing this improves the readability of the docstrings, and also allows other code (e.g. `mock`'s autospeccer) to read expected function signatures. Note that the actual function code, in `resources._resources.create_method` remains the same. It takes `*args, **kwargs` inputs. The function's signature gets patched after it's created. Because the code remains the same, we never actually transmit default values to the API.
I've set default values to the string "DEFAULT" in an attempt to indicate to users that the defaults in the function signature are different from the defaults in the API.
I'm running `raise_for_unexpected_kwargs` …
=> ENH Bind optional arguments to endpoints by name

CHANGELOG.md, civis/civis.py, civis/resources/_resources.py, civis/tests/test_resources.py
Certain endpoints with multi-word names like "match_targets" were being parsed as a single word.  This changes calls like
```python
client = civis.APIClient()
client.matchtargets.list()
```
To
```python
client = civis.APIClient()
client.match_targets.list()
```
Todo:
=> [CIVP-12839] Fixing name parsing of multiword endpoints

civis/futures.py
The default policy doesn't wait long enough between retries to successfully authenticate immediately after a Pubnub grant is refreshed.  Pubnub caches 403s so the client needs to wait at least 30 seconds before connecting again.  The exponential policy will wait long enough to resolve this particular issue.
=> [CIVP-12882] Update Pubnub reconnection policy

civis/civis.py
@stephen-hoover noticed that this warning appears when trying to tab complete the `client` object.   Easiest fix is to remove the warning as it is too noisy for the typical use case.
=> Removing deprecation warning for feature flags

CHANGELOG.md, civis/polling.py
This use of `except` is recording an exception and handling it in a way in which the user can deal with it, rather than hiding an exception inside a callback. `flake8` started complaining about it with the new v3.5 release.
=> MAINT Tell flake8 to ignore broad except

civis/io/_tables.py
The `civis.io._table.dataframe_to_civis` and `civis.io._table.csv_to_civis` functions were calling `file_to_civis` with both the `api_key` and `client` arguments. Those are redundant, and the `api_key` parameter is deprecated. Remove uses of `api_key` to avoid giving users a deprecation warning they can't control.
=> MAINT Don't call file_to_civis with deprecated api_key

civis/io/_tables.py
We were using a csv_to_civis example in the civis_file_to_table definition Switching to a correct example.
=> DOC: Use real civis_file_to_table example

CHANGELOG.md, docs/source/parallel.rst
The documentation on the Civis joblib backend assumed that users were already familiar with `joblib` and embarrasingly parallel computation, but not everyone is. Talk about the use case for the Civis joblib backend so that users can decide if this tool is useful for them or not.
=> DOC Add use case to parallel doc page

CHANGELOG.md, civis/resources/_resources.py, civis/tests/test_resources.py
Resolves #177.  This replaces hyphens with underscores in endpoint paths.
=> FIX: Parse all the hyphens

CHANGELOG.md, civis/futures.py, civis/io/_tables.py
If a SQL query fails, it can fail fast, sometimes faster than we can connect to our notifications channel. When we connect, request messages for the previous 30 seconds so that we can see if our job failed before we were able to finish setting up the connection to the notifications channel.
Two more small things fixed while I investigated this:
- Avoid unneeded API call in download_callback: The `CivisFuture` will already have results of the GET /scripts/sql call, so we don't need to make it again.
- Include polling_interval when getting headers: The `_include_headers` function should take a `polling_interval` parameter so that users can get the same polling behavior in the header `CivisFuture` as the primary query's `CivisFuture`.
=>  BUG Start pubnub subscriptions in the past

CHANGELOG.md, civis/io/_files.py, civis/tests/test_io.py
This facilitates uploads from or downloads to local files by allowing users to specify paths rather than file/buffer objects.  This particular type of polymorphism seems pretty well-accepted (cf. [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html)).
=> make it easier to upload local files

CHANGELOG.md, setup.py
The requirements file states that this library needs cloudpickle~=0.2, but the setup.py file states `cloudpickle>=0.2.0,<=0.3.99`. We don't need to have such a low upper limit in the setup.py file. Relax it to match the requirements.txt file.
=> BUG Relax requirement on cloudpickle version

CHANGELOG.md, civis/_utils.py, civis/io/_files.py, civis/io/_tables.py
- `dataframe_to_civis` now writes the dataframe to disk instead of an in memory buffer
- `file_to_civis` will re-write buffers that are not instances of io.BufferedReader to disk
- `_multipart_upload` will no longer re-write file parts to disk; instead it will open new file handles
=> [CIVP-13616] doubled disk usage in multipart upload

docs/source/user_guide.rst
The issue of how to create futures objects has come up a few times recently, so I think it'd be worth adding an example to the documentation.
=> add example of how to create civis futures to user guide

CHANGELOG.md, civis/cli/__main__.py, civis/cli/_cli_commands.py, docs/source/cli.rst
Add commands to the CLI to allow users to more easily open new notebooks. New commands are:
- launch : Create a new notebook, deploy it, and open it in a new brower tab.
- up : Start an existing notebook running and open it in a new browser tab.
- down : Stop a running notebook.
- open : Open an existing notebook in a new browser tab (if it's not running, don't start it).
These are usability improvements to make Civis Platform as a notebook backend even more transparent to users.
=> ENH CLI commands to open notebooks

CHANGELOG.md, docs/source/parallel.rst
Add more detail to the Sphinx documentation for the `parallel` module. Change the example of using the joblib backend so that it runs a user-defined function, to make it explicit that users can provide their own code instead of only running built-in functions.
=> DOC Improve parallel documentation

CHANGELOG.md, civis/ml/_model.py, docs/source/index.rst, docs/source/ml.rst
This PR changes the default `n_jobs` in `ModelPipeline.train` from 4 to `None`, so that it will be calculated dynamically by default. I also updated the docs to reflect that change, and documented `ModelPipeline`'s soft dependency on `glmnet` and `civisml-extensions` for accessing model objects.
=> ENH default to dynamically calculating number of training jobs in CivisML

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
When retrieving metadata, check the "warnings" key (present on all jobs) for any warnings which were recorded during the CivisML run. Reraise them as exactly as possible. We always attempt to download metadata after a job completes so that we can check for any errors, so we'll always see warnings from jobs as they complete.
=> ENH Re-raise warnings from CivisML

CHANGELOG.md, civis/parallel.py, civis/tests/test_parallel.py
Before we used 'civis' as the default. This means that containers are viral. Using the threading default is probably less confusing/surprising. IDK if we had this discussion before, but whatever the case, I am now convinced this is a better choice.
Closes #206 
@jmemich for viz
=> BUG make 'sequential' the default remote backend

CHANGELOG.md, civis/ml/_model.py, docs/source/ml.rst
This PR updates the documentation and `ModelPipeline` docstrings to reflect new features and defaults in CivisML 2.1.
=> Update documentation for CivisML

CHANGELOG.md, civis/ml/_model.py
The recommended use is to leave the default `n_jobs=None` so that CivisML can determine for itself how many jobs to use.
=> DOC Remove n_jobs from CivisML predict example

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
With CivisML v2, users can choose to skip the validation step. If that happens, there will be no validation metadata stored. This change lets the `ModelFuture` handle missing validation metadata files without issuing an error.
=> ENH Allow missing model validation metadata

CHANGELOG.md, civis/io/_tables.py, civis/tests/cassettes/ImportTests.test_dataframe_to_civis_with_index.yml, civis/tests/test_io.py
I hit a bug where I couldn't pass `index=True` to write my datframe's index with dataframe_to_civis.
This allows callers to overwrite the default `to_csv` kwargs if they'd like.
@keithing
=> In Which We Allow Callers to Over-Write Default to_csv kwargs in dataframe_to_civis

CHANGELOG.md, civis/cli/_cli_commands.py
@stephen-hoover, did you have this space there intentionally?  I just used `civis notebooks new`, and the space seemed odd.
=> remove extra space in the notebooks new CLI command output

CHANGELOG.md, civis/io/_files.py
Without this "%s", we see an error message for every fragment of multipart uploads. Also correct the order of two values in a multipart upload debug emit.
=> BUG Fix multipart upload log strings

CHANGELOG.md, civis/civis.py, civis/io/_tables.py, civis/tests/test_io.py
Fixes #219.  This PR allows users to pass in tables that contain periods in the schema and/or tablename, so long as they are in double quotes (as is the SQL convention).  For instance `schema."my.table"` or `"sch.ma"."tab.le"`.
If a user passes `table` without a schema, there will now be a more helpful error as well.
=> Adding robust parsing

CHANGELOG.md, civis/civis.py, civis/io/_tables.py, civis/tests/test_io.py
The `_robust_schema_table_split` is pretty useful, and users may wish to use it themselves. Promote to a public function with a clearer name. Also modify the function so that a single table name, without a schema, is a valid input. In such a case, return `None` for the schema name.
Closes #223 .
I'm open to name suggestions, or if this function should live in a different namespace. Or if you think that the function shouldn't be public after all.
=> ENH Public schema/tablename-splitting function

.gitattributes, CHANGELOG.md
Let git know how we prefer to merge changelogs; this will mean fewer merge conflicts for contributors.
=> MAINT Add changelog rule to gitattributes

CHANGELOG.md, docs/source/io.rst
Looks like we forgot to add a line to the docs about this function.  I imagine there is a way to programmatically add all function from a namespace, we might want to look into that in the future.
=> DOC: Adding missing function documentation

CHANGELOG.md, civis/futures.py, civis/parallel.py, civis/tests/test_futures.py, docs/source/parallel.rst
It can be useful for child jobs to know which job created them. This injects environment variables into child jobs which give the job and run ID of the creator. Note that the joblib backend uses the `_ContainerShellExecutor` to launch its jobs, so this change affects it as well. Custom scripts will only have parent job and run IDs if the template provides that parameter. There's no way to inject environment variables which the template creator didn't explicitly allow for.
=> ENH Include parent job and run ID in children

CHANGELOG.md, docs/source/ml.rst
A client recently tried to use a predefined MLP, but ran into errors because they thought we used the sklearn MLP estimators (reasonable, since the muffnn and sklearn estimators have the same names). I moved the dependencies section to the top to clarify where we are not using sklearn, and explicitly include the module in the pre-defined models table for non-sklearn estimators.
=> DOC clarify when non-sklearn estimators used in CivisML

CHANGELOG.md, civis/ml/_model.py
CivisML v2.2 will add the ability for users to subset model predictions, as a way to save time and space. Add this parameter to `ModelPipeline.predict`.
=> ENH Add "dvs_to_predict" param to ModelPipeline.predict

CHANGELOG.md, setup.py
We want to include JSON files with installations of the API client; there are JSON blobs with caches of API endpoints which are useful for testing. The `data_files` argument installs the JSON files when running `python setup.py install`, but they don't come when you run `pip install`. Setting `include_package_data=True` will include everything in the `MANIFEST.in`, including the JSON files.
=> BUG Include JSONs in package data

CHANGELOG.md, civis/io/_files.py
I'd written some code like
```python
with tempfile.NamedTemporaryFile() as temp:
civis.io.civis_to_file(file_id, temp)
df = pandas.read_csv(temp.name)
```
with a bit of extra logic for `read_csv`-ing in chunks to keep from going out of memory.
Because `temp` wasn't being flushed, I would occasionally get errors from unexpected end of files. 
I'm not sure if that's expected behavior or not (if I'm passing the buffer to `civis_to_file` should I be expected to flush it myself?) but flushing them `civis_to_file`-side seems harmless at worst and bug-avoiding at best.
@mheilman
=> In Which We Flush Buffers After Finishing Writing to Them

CHANGELOG.md, docs/source/ml.rst
The next CivisML release (v2.2) will specify a max_depth for tree ensembles and will remove `max_depth=None` from depths searched during hyperband hyperparameter optimization.
=> DOC Update max_depth settings for CivisML

civis/ml/_model.py, civis/ml/tests/test_model.py, docs/source/ml.rst
If you train a scikit-learn compatible estimator outside of Civis Platform, you can use this to upload it to Civis Platform and prepare it for scoring with CivisML. There's a new Custom Script which will introspect metadata necessary for CivisML and make itself appear sufficiently like a CivisML training job that it can be used as input to a scoring job.
=> ENH Register models trained outside of Civis Platform

CHANGELOG.md, civis/tests/test_io.py
The `test_civis_to_file_local` function had been writing a file to disk which remained behind after the test. Additionally, `called_once_with` is not a method of a `Mock` object; it becomes its own `Mock`, which takes any paramter given and always evaluates to `True`. Change all instances of those calls to `assert_called_once_with`. Add `autospec` to `patch` calls where possible to test that mocked functions are being called with valid arguments.
=> BUG Fix tests in test_io

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
The ``ModelPipeline`` will now create v2.2 models in CivisML by default.
=> ENH Add CivisML v2.2 template IDs

CHANGELOG.md, README.rst
This add instructions for adding the environmental variable `CIVIS_API_KEY` in Windows.
=> DOC: Windows api key

CHANGELOG.md, README.rst, docs/source/index.rst
This PR merges the repo's top-level `README.rst` and the Sphinx docs-specifics `index.rst`. The end result is that `README.rst` is the single source of truth for such items as installation and API keys, whereas `index.rst` is now minimal and contains (i) markers that draw text from `README.rst` and (ii) items specific to Sphinx docs such as `toctree`.
For the new `README.rst`, please check it out at my fork: https://github.com/jacksonllee/civis-python/blob/coalesce-readme-index-rst/README.rst
For the new `index.rst`, the compiled Sphinx docs will look like this:
Resolves #253.
=> DOC Coalesce README.rst and index.rst

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
Since `pandas` v0.23.1 (specifically from https://github.com/pandas-dev/pandas/pull/21300), if a file-like object is passed into `df.to_csv`, the object must have the method `getvalue`, or else an `AttributeError` is raised (which is what we have observed from #258). An `io.TextIOWrapper` object doesn't have the method `getvalue`, which caused the latest build failures in #258. This PR switches to `io.StringIO` instead.
=> BUG A file-like object as arg to df.to_csv must have the method getvalue

CHANGELOG.md, appveyor.yml, civis/ml/tests/test_model.py, civis/tests/test_io.py, civis/tests/test_polling.py, dev-requirements.txt
IT support has turned on AppVeyor for CI in Windows. This PR configures that, based on what we already have for Circle CI.
Resolves #10.
=> MAINT Configure Windows CI using AppVeyor

dev-requirements.txt
pyarrow doesn't have wheels for 3.4 now (see https://pypi.org/project/pyarrow/#files), so the build for master fails (see #264) because it can't install pyarrow, which is required for `feather-format`.
Ideally, we'd make it so travis could build arrow if necessary, but that seems nontrivial, so I'm continuing with the less-than-great solution of not testing feather when a wheel isn't available.
=> update feather-format in dev-requirements.txt

tools/smoke_tests.py
The smoke tests were failing because rows would come back in a different order.  This change makes it so that the order shouldn't matter.
=> make smoke tests not fail if row order varies

CHANGELOG.md, docs/source/conf.py, docs/source/parallel.rst
https://pythonhosted.org/joblib doesn't exist anymore. The joblib documentation has moved to the readthedocs site.
=> DOC joblib documentation has moved to readthedocs

CHANGELOG.md, civis/io/_tables.py, civis/tests/test_io.py
- forward the client kwarg from `civis_to_multifile_csv` to `civis_to_file`
- fix a new flake8 error: `civis/io/_tables.py:961:11: W605 invalid escape sequence '\s'`
@elliothevel 
@keithing what does the release process look like? Got a bug I was hoping to get a fix out for soon.
=> In Which We Pass the API Client Through From civis_to_multifile_csv

civis/io/_files.py, civis/tests/test_io.py
It also fixes a related bug in file_to_civis where the buffer was reset to 0 rather than the original position when retrying.
Fixes #272.
=> Add a retry for downloading files via civis.io.file_to_civis

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py, dev-requirements.txt
This PR fixes a bug to ensure compatibility with CivisML v2.2.2. In 2.2.2, CivisML does not create an index column when the user does not specify a primary key. This fix forces `civis.ml.ModelFuture.table` to check for a primary key before determining if the first column is an index or not. Unfortunately, the metadata structure is different for training and prediction, so this fix includes two complicated hardcoded paths through the metadata, but I don't see any way around this. I tested the fix on three actual model jobs (training with pkey, predict with pkey, predict without pkey) and it behaved as expected for all three.
=> BUG check for primary key to determine how to read index

.travis.yml, CHANGELOG.md, README.rst, appveyor.yml, setup.py
This PR adds tests for Python 3.7 compatibility. #266 mentions updating the documentation, but I couldn't find anywhere in the docs that explicitly mention compatible Python versions. Happy to add a section if that would be helpful.
Fixes #266.
=> MAINT add python 3.7 compatibility

CHANGELOG.md, civis/response.py, civis/tests/test_response.py
The Scripts and Jobs run cancellation endpoints (e.g., DELETE /jobs/{job_id}/runs/{run_id})
return an empty response with a 202 error code, which is reasonable, I think.
The client currently raises a CivisClientError("Unable to parse JSON from response", ...) in that case because it only expects empty responses for 204 or 205.  This fixes that so that users will be able to use the client with those endpoints.
=> Fix handling of empty responses from run cancellation endpoints.

CHANGELOG.md, docs/source/io.rst
Users have reported having trouble finding the documentation of `civis.io.split_schema_tablename`. Let's surface it.
=> DOC Surface civis.io.split_schema_tablename

CHANGELOG.md, requirements.txt, setup.py
* Fixes DeprecationWarning in python 3.7
* Also fix pubnub ~= version that is no longer recognized in pip 19.0
This happens when jsonref 0.1 is used, but the warning is now fixed in jsonref 0.2:
```python
% python3 -W default
Python 3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import civis
/usr/local/lib/python3.7/site-packages/jsonref.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
=> Upgrade dependency of jsonref

docs/source/user_guide.rst
It was a bit surprising to me that the documentation treated `concurrent.futures.wait` the same as `futures.result()`, but the former doesn't raise an exception and the latter does. Maybe there's a better solution than this, but I thought I'd at least add some clarification.
=> Clarified exception behavior of futures

CHANGELOG.md, civis/parallel.py, civis/tests/test_parallel.py, requirements.txt, setup.py
It turns out our incompatibility with newer versions of `joblib` were due to mocking we were doing in the tests.
In v0.12, a `joblib` change meant that it relies on callback from the result object to decide when to terminate batched consumpution of inputs. Two of our tests mock the result object, which means that joblib's supplied callback doesn't get called. Set `n_jobs=1` so that `joblib` consumes the inputs all at once and doesn't need the callbacks.
This PR also relaxs requirement on the `joblib` and `cloudpickle` version numbers, and modifies our custom backend to include some new backend features.
Closes #296
=> Compatibility with joblib > 0.11

CHANGELOG.md, civis/parallel.py
The `test_parallel.test_setup_remote_backend` function would give an error if scikit-learn was not installed. This is because we try to mock the `parallel._sklearn_reg_para_backend` function, and that doesn't exist if scikit-learn isn't installed. Fix by ensuring that attribute is always defined.
Closes #245 .
=> BUG Fix unintentional dependency on scikit-learn for testing

CHANGELOG.md, requirements.txt, setup.py
Use newer versions of these packages in tests. It seems to work.
Closes #286 .
=> MAINT Relax requirements on click and jsonschema

CHANGELOG.md, civis/__init__.py
Import `utils` into `civis` so that users can access `civis.utils.run_job` after an `import civis` import. Many users expect this and are surprised when it's not available.
=> ENH utils module available from civis namespace

CHANGELOG.md, civis/io/_files.py
We have functions to download Civis File objects and convert them to a DataFrame or a JSON object. Add functions to go the other way. In particular, users often expect the `dataframe_to_file` function and are surprised that it doesn't exist.
Closes #262 .
=> ENH dataframe and json to-file conveniences

CHANGELOG.md, civis/_utils.py
Collect the user's Python version along with the API client version. This can be useful in evaluating maintenance requirements going forward.
Closes #255 .
=> ENH Include Python version in User-Agent string

CHANGELOG.md, civis/base.py, civis/civis.py, civis/tests/test_base.py
As a convenience, keep track of the last response received from the Civis API.
Closes #153 .
=> ENH last_response attribute for the APIClient

CHANGELOG.md, requirements.txt, setup.py
Cloudpickle v1.2 released on June 7th, and our Python 3.4 build started failing. Set in requirements that Python 3.4 needs v1.1 or older.
=> MAINT Restrict cloudpickle version in Python 3.4

.travis.yml, CHANGELOG.md
Python versions >=3.7 require OpenSSL 1.0.2+, which is not available in Trusty (the default environment). Switch to using Xenial (Ubuntu 16.04) for all of our tests, instead of only for v3.7. It seems that the sudo mode is no longer required.
=> TST Test in Xenial environment

CHANGELOG.md, civis/_deprecation.py, civis/tests/test_deprecate.py
In Python v3, multiple layers of the deprecation decorator work as expected. But we run into problems with Python v2.7 (apparently due to missing features in the `Signature` class). If the decorator takes multiple parameter names, it's more complex, but will be compatible with more Python versions.
=> COMPAT Deprecation decorator takes multiple parameter names

CHANGELOG.md, civis/ml/__init__.py, civis/ml/_helper.py, civis/ml/tests/test_helper.py
This PR adds a helper function to list a user's models (training, prediction, or both).
=> ENH helper function to list models

CHANGELOG.md, civis/cli/__main__.py, civis/tests/test_cli.py
The CLI's name parsing was failing on /aliases/{object_type}/{alias}. Switch to using the version of this function which already existed in `civis.resources`, with some small munging to account for the CLI's naming style.
Also add a test which will fail if the CLI generates other similar warnings in the future. It should stay a warning in the code, so that changes to the Civis API don't expose bugs which render the CLI unusable, but this should cause our tests to fail until we fix it.
Closes #298 .
=>  BUG Use APIClient method name parsing for CLI

CHANGELOG.md, civis/io/_files.py, civis/tests/test_io.py
This main issue that this PR aims to address is to avoid having to write client code like `civis.io.file_to_civis('foobar.txt', 'foobar.txt')`, where the second arg `name` is obligatory currently (as of v1.11.0) but seems unnecessary. I think it'd be perfectly reasonable to allow code like `civis.io.file_to_civis('foobar.txt')` where `name` can internally be inferred from the basename of the given file path -- this is what this PR implements.
=> ENH Optional `name` arg in civis.io.file_to_civis

CHANGELOG.md, civis/io/_databases.py, civis/io/_files.py, civis/io/_tables.py
This adds some debug logging calls in a few spots in `civis.io` to facilitate tracking of underlying job and file IDs.
=> Added debug logging to some `civis.io` functions.

CHANGELOG.md, civis/ml/_model.py
`ModelPipeline.register_pretrained_model` should keep the user-supplied estimator indefinitely on the Civis Files endpoint.
=> [PARO-745] register_pretrained_model should keep estimator indefinitely

CHANGELOG.md, README.rst, civis/__init__.py
This PR adds a note in the README that Python 2 will no longer be supported as of April 1, 2020. The Python client will also issue a warning to Python 2 users when imported. I've attached an image below of what this looks like. One wrinkle here is that interpreters ignore deprecation warnings by default, so this doesn't show up unless the user disables that default. I don't know that there's a good way around this problem.
I initially tried writing a unit test for this, but I couldn't get it to pass, I think because pytest imports the library as it's setting up the tests. The warning did show up in the pytest warning summary, but was not captured in the unit test. I confirmed manually that the warning issues for Python 2 and does not issue for Python 3.
Closes #332 .
=> DEP deprecation warning in readme and on import

CHANGELOG.md, civis/io/_files.py, civis/tests/test_io.py
Raise a more informative exception when calling `civis.io.file_to_dataframe` on a file with no url (which likely means the file is expired). I went with a `ValueError` here but could change it if a different exception would be easier to understand. This error check is pre-empting a `ValueError`, since the error comes from reading a csv from `None`.
Closes #336.
=> ENH more informative error for expired files

CHANGELOG.md, civis/io/_tables.py
This PR removes "optional" as a marker for the mandatory `sql` argument in several sql-related I/O functions, as raised in #335 .
=> DOC remove 'optional' from mandatory args

CHANGELOG.md, civis/io/_tables.py, civis/tests/test_io.py, dev-requirements.txt, setup.py
**JIRA Ticket:**
[CIVP-15320](https://civisanalytics.atlassian.net/browse/CIVP-15320)
**Summary:**
Adding the max_file_size parameter to the civis.io.civis_to_multifile_csv
**Testing:**
Notes:
used the `civis.io.civis_to_multifile_csv` function to create files with different max file sizes and verified the file size
sql scripts are: [55697443](https://platform.civisanalytics.com/spa/#/scripts/sql/55697443) and [55697108](https://platform.civisanalytics.com/spa/#/scripts/sql/55697108)
**Additional Info:**
=> [CIVP-15320] Add max_file_size param to civis_to_multifile_csv

CHANGELOG.md, README.rst, civis/__init__.py
Adds a `FutureWarning` that Python 3.4 will be deprecated along with Python 2. Closes #339. I considered adding 3.5 to the list, since it's reaching EOL in 2020, but I figured it's better to be conservative about dropping support.
I don't know of a way to test that this code works within pytest (see discussion in #333 ), but I've attached screenshots confirming that the warning is issued in 3.4 and not in 3.6.
=> 339 3.4 deprecation

CHANGELOG.md, civis/ml/_helper.py, civis/ml/_model.py, civis/ml/tests/test_helper.py, civis/ml/tests/test_model.py, docs/source/ml.rst
This PR decouples CivisML from civis-python with respect to the following:
* PARO-685: Use template ID aliases, so that a new CivisML release doesn't require a new civis-python release anymore.
* PARO-744: Document CivisML dependency versions on Zendesk rather than in civis-python's Sphinx docs, so that we can update Zendesk independently when CivisML is updated for the modeling dependencies (civis-python's Sphinx docs don't update unless a new civis-python release is made).
@stephen-hoover You are the appointed reviewer, since I think you're the person who has thought about the use of aliases for this scenario the most.
=> [PARO-685] [PARO-744] Decouple CivisML from civis-python: Use template ID aliases and move docs to Zendesk

civis/__init__.py, civis/resources/_resources.py, civis/service_client.py, civis/tests/test_service_client.py
Adding ServiceClient() method which takes a service id, optional base path (default is None), and optional swagger endpoint (default is '/endpoints'), then creates a client from the api spec and endpoints.
A lot of the work is being done in the helper functions and Endpoint class for the original APIClient, but small changes were needed in a few cases (mostly in regards to the url and making requests). These changes are overridden by the ServiceClient and ServiceEndpoint class.
=> [Serd-1694] service client

CHANGELOG.md, civis/ml/_model.py, tools/smoke_tests.py
This PR is a follow-up of #341, which makes strong assumptions about what CivisML alias objects exist on Civis Platform.
Before this PR, the smoke test for CivisML modeling used the default scenario of not specifying `civisml_version` for `civis.ml.ModelPipeline` (which would use the latest CivisML version in production). This PR makes the CivisML modeling smoke test also run on an explicitly specified `civisml_version` as well, which would access different CivisML alias objects than the unspecified `civisml_version` does.
While working on this PR, I uncovered a bug where `civis.ml.ModelPipeline`'s `civisml_version` param with a non-existent CivisML version did not raise the expected error of "the specified CivisML version doesn't exist". Bug fixed at 0eb8dd4.
=> [PARO-685] Smoke tests for different CivisML alias objects

CHANGELOG.md, requirements.txt, setup.py
Updating `cloudpickle` and `joblib` versions following discussion in #329.
I manually tested this on Python 3.6.8 with up-to-date `cloudpickle` and `joblib` versions, and @jacksonllee did the same for Python 3.7.
=> MAINT update dependencies for CivisML

README.rst
This is just to try to have consistency with naming elsewhere, particularly with the R client.
Related: https://github.com/civisanalytics/civis-r/pull/222
=> Civis API Client -> Civis Platform API Client in readme

civis/resources/_resources.py, civis/tests/test_resources.py
One thing to note:
- We'll have code that asserts that an endpoint must have both `deprecated` and `warning` set, not one or the other.
This PR will close #345.
=> handle deprecated endpoints

civis/service_client.py
In SERD-1816 we are hoping to catch timeouts on our survey-toolbox service API endpoints. In order to do so, we have to raise an API error rather than a value error so we can check the response. 
cc @leeacto @ggarcia-civis for viz
=> [SERD-1816] Service Client Error Handling

CHANGELOG.md, docs/source/ml.rst
The documentation for the CivisML version implies that the major use of the `civisml_version` parameter (added in #341) is to use an older version of CivisML, which seems slightly misleading. I'm updating the docs to clarify that it's about pinning the version for production work as a more probable use case.
The parallel PR for civis-r is https://github.com/civisanalytics/civis-r/pull/225
=> [PARO-685] DOC update language for CivisML version

CHANGELOG.md, README.rst, civis/cli/__main__.py, civis/cli/_cli_commands.py
* Adds `civis jobs follow-log` and `civis jobs follow-run-log`
* Like `tail -f` for job run logs, closely mirroring the output of run logs on the web UI
<details><summary>Demo GIFs</summary>
<p>
</p>
</details>
=> ENH CLI live log tail

CHANGELOG.md, civis/futures.py, civis/parallel.py, civis/tests/test_futures.py, civis/tests/test_parallel.py
This addresses a bug where submitting jobs from a parallel backend from `infer_joblib_backend` failed when used in a child job where `CIVIS_PARENT_JOB_ID` and `CIVIS_PARENT_RUN_ID` were set. Those parameter names would be duplicated, which causes platform to reject the job.
I tweaked `infer_joblib_backend` because the issue pertains to use of that function.  I decided to also replace rather than append parent job parameters in ` _ContainerShellExecutor.__init__` [here](https://github.com/civisanalytics/civis-python/blob/adc87f1a8ec2c7501b611f9213054234cccc14f1/civis/futures.py#L562-L568) because the behavior there also seemed problematic.
To do:
=> avoid duplicate parent job parameters when inferring joblib backend

CHANGELOG.md, civis/cli/_cli_commands.py, civis/tests/test_cli.py
Before this change, running `civis sql` with some cells being NULL results in this error:
```py
File "/Users/apollak/dev/civis-python/civis/cli/_cli_commands.py", line 166, in _str_table_result
[[len(_v) for _v in _r] for _r in [cols] + str_rows])
File "/Users/apollak/dev/civis-python/civis/cli/_cli_commands.py", line 166, in <listcomp>
[[len(_v) for _v in _r] for _r in [cols] + str_rows])
File "/Users/apollak/dev/civis-python/civis/cli/_cli_commands.py", line 166, in <listcomp>
[[len(_v) for _v in _r] for _r in [cols] + str_rows])
TypeError: object of type 'NoneType' has no len()
```
=> Print NULL for `civis sql` output with Nones instead of crashing

CHANGELOG.md, civis/parallel.py
`sklearn==0.22.0` sets the default for `n_jobs` to `None` for `LogisticRegression` models https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression
This is a breaking change from `0.19.x` which set it to 1. The `joblib` library accounts for this already in a recent bug fix but we don't in our custom backend. Here's the fix.
=> account for when n_jobs is none

CHANGELOG.md, civis/tests/mocks.py
* Calling create_client_mock() repeatedly takes about a second each time it's called. This is because calling APIClient(local_api_spec=...) creates new resource classes from the endpoints JSON every time, instead of using the normal resource cache like it does when calling APIClient() without a local_api_spec.
Total test time on Travis (this PR is on top, previous build is bottom):
Not sure if this deserves a changelog entry?
=> Speed up repeated invocations of create_client_mock

CHANGELOG.md, README.rst, setup.py
We were not able to build distributions with `twine` for a new release, because `twine` doesn't allow duplicate references in the reStructuredText-formated README (not sure why this didn't come up before for previous releases, but I don't think we're interested in digging into this now). Also fixed is the missing `long_descritption_content_type` kwarg in `setup.py`, which `twine` threw a warning for.
With this PR, locally I tested it by building the source distribution and checking with `twine` again. Everything looks good now:
```
$ twine check dist/civis-1.13.0.tar.gz 
Checking dist/civis-1.13.0.tar.gz: PASSED
```
=> Fix readme and setup.py to appease twine

CHANGELOG.md, requirements.txt, setup.py
=> Fixed/relaxed version specifications for click, jsonref, and jsonschema.

CHANGELOG.md, civis/io/_tables.py, civis/tests/test_io.py
**JIRA Ticket:**
[APIC-273](https://civisanalytics.atlassian.net/browse/APIC-273)
**Summary:**
Adding the table_columns parameter to io methods.
**Testing:**
Manual Tests
Notes:
**Additional Info:**
=> [APIC-273] Add Table Columns Parameter

CHANGELOG.md, civis/futures.py, civis/tests/test_futures.py
This PR adds a new method to `CivisFuture` objects, `.outputs()`, which blocks on job completion and returns the run outputs. I kept it as minimal as possible to make it generalizeable and easy to maintain, while still making it easy to maintain.
I tested the method manually on succeeded and failed container scripts using both `CivisFuture` and `ContainerFuture`, and also tested on a successful sql script. It's always challenging to add meaningful unit tests to the API client, so I'm happy for feedback on the unit testing I added.
=> ENH add method to retrieve run outputs from future

CHANGELOG.md, civis/service_client.py, civis/tests/test_service_client.py
This PR moves API spec parsing for services outside of the `ServiceClient` object. This allows a user to parse a spec without an API key.
=> ENH parse_service_api_spec outside of serviceclient object

CHANGELOG.md, civis/service_client.py, civis/tests/test_service_client.py
This PR fixes a bug in civis-python 1.14.0 that breaks autospec generation. The issue arises because the root path is not passed to the parsing function when generating classes. This PR also replaces an undefined variable with the defined variable in a now deprecated function.
=> [APIC-278] bugfix root path in parse

README.rst
This is just following up after #357 and the 1.14.x releases, to remove the outdated deprecation warning.
=> remove python 2 deprecation warning

CHANGELOG.md, civis/io/_tables.py
In this PR, we explicitly note in the import methods in the `civis.io` module that primary key columns cannot be null. We are concurrently updating the API documentation to reflect this as well.
=> Add additional detail on primary_keys

CHANGELOG.md, civis/cli/__main__.py, civis/tests/test_cli.py
When using the python API client CLI tool a command which fails can still exit with a 0 exit code. This can lead Platform to mark jobs which didn't successfully complete with a green checkmark or to mistakenly progress workflows when a step didn't work.
MWE:
Running 
```
civis tables post-scan some_db_id some_schema some_table
```
Generates logs:
```
2020-05-05 04:14:37 PM code: 404
2020-05-05 04:14:37 PM error: not_found
2020-05-05 04:14:37 PM errorDescription: The requested resource could not be found.
```
But the job is still marked as successful.
=> [APIC-238] Make CLI exit code nonzero when response status code != 2xx

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py, civis/run_joblib_func.py, civis/tests/test_io.py
=> fix some minor issues that flake8 3.8 finds

CHANGELOG.md, civis/io/_tables.py, dev-requirements.txt
There was no way for users to avoid this deprecation warning when calling `civis.io.civis_file_to_table`, and it was also triggered by other functions which called `civis_file_to_table` (such as `dataframe_to_civis`). The original thought had been to replace the singular `file_id` parameter with a plural `file_ids` parameter in v2, but per discussion in #360, the singular will be acceptable.
Closes #360.
=> DEP Remove file_id deprecation warning

CHANGELOG.md, requirements.txt, setup.py
From the pubnub changelog, they fixed all the keyword clashes (for async and await) since the v4.1.2 released in Sept 2018. 
I don't fully understand all the reasons I ran into this issue (why an older pubnub version was pulled in on my fresh install), but it's quick change.
=> [APIC-300] bump minimum pubnub version

docs/source/cli.rst
The CLI command is `civis jobs follow-log` and `civis jobs ollow-run-log` not `civis jobs follow-logs` / `civis jobs follow-run-logs`
=> Correct follow-logs typo

civis/io/_tables.py, civis/tests/test_io.py, docs/source/cli.rst
[APIC-305](https://civisanalytics.atlassian.net/browse/APIC-305)
Ensure data types are detected when the destination table does not exist or it is being dropped and table_columns are provided but do not contain a sql_type for every column.
=> [APIC-305] Require sql_type for every column when table_columns is provided

CHANGELOG.md, civis/io/_tables.py, civis/tests/test_io.py
In the `civis.io.civis_file_to_table` function, the Python API client appears to tell platform to change SQL types like `VARCHAR(1)` in the `table_columns` argument to more generic values like `VARCHAR(1024)` when there are multiple files.  The behavior seems reasonable when data types are automatically inferred (i.e., when `need_table_columns` is true), as noted in the code comment, but if the user has specified a dtype with specific length like `VARCHAR(1)`, the import should just use that.
=> [APIC-313] retain specific sql types in civis_file_to_table

CHANGELOG.md, civis/io/_tables.py
Update changelog to reflect change in https://github.com/civisanalytics/civis-python/pull/400.
=> [APIC-305] Require sql_type for every column when table_columns is provided (CHANGELOG)

.travis.yml, CHANGELOG.md, README.rst, civis/polling.py, setup.py
'Python 3.5 will reach its "end of life" at the end of September 2020.' (https://www.python.org/downloads/release/python-3510/)
=> [APIC-284] remove python 3.5 support since it is reaching EOL

CHANGELOG.md, civis/resources/_resources.py
This adds some missing API resources to the list of resources that the sphinx doc generation code uses to create https://civis-python.readthedocs.io/en/stable/api_resources.html.  Using the list to filter the resources is a way to avoid including, e.g., "admin" endpoints that users aren't going to be interested in. Maybe we should eventually just include all the resources in the doc, but I didn't want to make that larger change at the moment.
=> [APIC-76] include services and other missing resources in sphinx docs

CHANGELOG.md, civis/response.py, civis/tests/test_response.py
This fixes a bug where a column named "update" would cause response parsing to fail for `/tables` endpoints.
The `civis.response.Response` provides convenient access to response attributes (e.g., `response.attrib` as opposed to `response['attrib']`). In retrospect, perhaps it'd have been better not to have that functionality recur all the way down the response structure (or at least not into user-provided table info), but that ship has sailed, and in order to minimize breaking changes, this PR should preserve the existing functionality and avoid the bug.
=> [APIC-306] Fixed a bug in parsing responses that included "update" as a key

CHANGELOG.md, civis/resources/_resources.py, civis/tests/test_resources.py
Some of our users have found it misleading that default arguments are always set to 'DEFAULT'. Also some of our endpoints do use default arguments and it would be nice to be able to include that in the signature if specified in the swagger.
The 'default' property is included as swagger 2.0 format as optional (https://swagger.io/docs/specification/2-0/describing-parameters/), but it was not being read-in as part of the civis-python parsing process.
This PR uses that default value if present in the swagger, if not it uses the previous 'DEFAULT' string because not setting a default for kwargs will cause the signature to read it as required.
here is an example with our sdkclient.weights.list() method which takes some optional arguments to filter by.
Before (all set to 'DEFAULT'):
After (real …
=> [HACK-465] Use default arguments from swagger when provided

CHANGELOG.md, civis/io/_tables.py, civis/tests/test_io.py
The client is looking for the `table_columns` parameter to be a list of dictionaries, each of which has a "name" key and which optionally also have a "sql_type" key. If Civis Platform needs to know types, and there is no "sql_type" key in any of the dictionaries, the client will silently replace a user-provided `table_columns` with an inferred `table_columns`. The docstring claims that the expected formatting is "sqlType", but "sqlType" keys will be ignored.
Fix the docstrings to use snake case instead of camel case, and add a check on the `table_columns` input to prevent mistakes or typos.
=> BUG Correct sql_type doc casing and check input for typos

CHANGELOG.md, civis/cli/_cli_commands.py
Civis Platform no longer supports Python 2 notebooks (currently Python 3 and R), but the CLI was still presenting Python 2 as an option.
=> MAINT Remove unsupported Python 2 notebook option

CHANGELOG.md, civis/futures.py, civis/ml/_model.py, civis/ml/tests/test_model.py, civis/tests/__init__.py, civis/tests/mocks.py, civis/tests/test_futures.py, civis/tests/test_parallel.py
The Civis API currently returns `'error': None` when a Python/R/container script fails, so API client users don't get any information about what caused the failure. CivisML works around this by returning error logs to the user in these cases. This PR moves this behavior from `ModelPipeline` to `ContainerFuture` so that users can get more informative errors when running jobs outside of CivisML as well.
This is something of a workaround, especially since R client users won't get the benefits. Longer-term, we'd like to get more informative errors directly from the API.
=> ContainerFuture propagates error from logs

CHANGELOG.md, civis/base.py, civis/futures.py, civis/ml/tests/test_model.py, civis/polling.py, civis/tests/mocks.py, civis/tests/test_futures.py
This PR adds the job ID and run ID to the exception message of `CivisJobFailure` coming from a `CivisFuture` object.
=> [CIVP-19775] ENH add job and run ID to CivisJobFailure from CivisFuture

CHANGELOG.md, civis/io/_tables.py
`civis.io.civis_file_to_table` assumes the internal CSV preprocessing jobs always return run outputs, but this assumption breaks down if CSV preprocessing fails with no run outputs and therefore leads to an uninformative "list index out of bounds" error. This PR handles this error and provides a better error message to aid debugging.
=> [CIVP-22464] BUG Better error message when CSV preprocessing fails in `civis_file_to_table`

CHANGELOG.md, civis/civis.py
civis-python v1.15.0, released in Sept 2020, reworked the retry logic (https://github.com/civisanalytics/civis-python/pull/401), which made the `retry_total` parameter of `civis.APIClient` actually not used by anything. This present PR officially deprecates this parameter.
=> [CIVIS-1642] FIX deprecate the inactive `retry_total` parameter of `civis.APIClient`

CHANGELOG.md, civis/base.py, civis/civis.py, civis/cli/__main__.py, civis/cli/_cli_commands.py, civis/resources/_resources.py, civis/response.py
`assert` statements shouldn't be used in the actual, non-test code, since they can be disabled by the `-O` flag: https://docs.python.org/3/using/cmdline.html#cmdoption-O It's not clear how likely folks would run Civis-related code with this flag on, but it's better to convert these `assert` statements into conditional statements with exception raising.
=> [CIVIS-1609] FIX no `assert` statements in non-test code

CONTRIBUTING.md
This PR updates `CONTRIBUTING.md` to clarify how to install civis-python locally and the differences between Civis vs non-Civis employees. Here's how GitHub renders the changes from this PR branch: https://github.com/civisanalytics/civis-python/blob/civis-1656-contributing-docs/CONTRIBUTING.md
=> [CIVIS-1656] DOC update `CONTRIBUTING.md`

civis/io/_tables.py
Clarify table_columns parameter per https://civisanalytics.atlassian.net/browse/APIC-280
=> [APIC-280] DOC clarify table_columns param in civis.io functions

CHANGELOG.md, civis/resources/_resources.py, civis/tests/test_resources.py
Ticket: https://civisanalytics.atlassian.net/browse/CIVIS-1614
These changes are to specify the civis response type (regular vs paginated) in https://civis-python.readthedocs.io/en/v1.15.1/api_resources.html
TODO: update CHANGELOG, if this implementation is good.
=> [CIVIS-1614] DOC specify response type in Returns documentation.

CHANGELOG.md, civis/_utils.py
This PR adds job and run IDs as custom headers in API calls, so that jobs and runs are more easily identifiable by their IDs through Civis Platform's logging.
=> [APIC-66] ENH add job and run IDs as custom headers in API calls

CHANGELOG.md, civis/io/_tables.py, civis/resources/_resources.py, civis/tests/test_resources.py, docs/source/conf.py, docs/source/user_guide.rst
Several Civis API endpoints are multi-word (e.g., "Match Targets", "Json Values"), but [their details don't show up in the Sphinx docs](https://civis-python.readthedocs.io/en/v1.15.1/api_resources.html). This PR fixes this problem. Also fixing a couple other small documentation-related things.
=> [CIVIS-1787] DOC show details for multi-word API endpoints in Sphinx docs

CHANGELOG.md, docs/source/parallel.rst
This PR calls out the default value of `joblib.Parallel`'s `pre_dispatch` to be `"2*n_jobs"` (not `"n_jobs"`) in the Sphinx docs.
Closes #361
=> [CIVIS-1510] DOC call out `joblib.Parallel`'s `pre_dispatch`

CHANGELOG.md, README.rst, examples/PythonAPIClientDemo.ipynb
MacOS has switched to ZSH as the default shell, but our docs still mention `.bash_profile` for the API key set-up. This PR updates the docs.
=> [CIVIS-1851] DOC update info about MacOS shell config file

CHANGELOG.md, civis/io/_tables.py
This PR makes explicit the implicit requirement that Civis files in civis.io.civis_file_to_table must be in CSV-like format.
Closes #422 
Screenshot of changes:
=> [CIVIS-1509] DOC improve documentation of input to `civis.io.civis_file_to_table`

.circleci/config.yml, CHANGELOG.md, civis/_utils.py, civis/io/_files.py, civis/io/_tables.py, civis/parallel.py, civis/run_joblib_func.py
This PR turns on security checks with `safety` and `bandit`. The checks are run on CircleCI builds.
=> [CIVIS-1678] MAINT turn on security checks with `safety` and `bandit`

CHANGELOG.md, civis/io/_tables.py
Tested and confirmed that .gz files can be used in civis.io.civis_file_to_table and added a section to the docstring.
=> [CIVIS-1869] DOC Add confirmation of compressed file usage in civis_file_to_table

CHANGELOG.md, civis/io/_files.py
This change adds logic to the civis.io.file_to_civis function that warns the user if they are using the function on a file with a size of zero bytes.
=> [APIC-296] MAINT Python client's file_to_civis should not warn about file size of 0 bytes

.circleci/config.yml, CHANGELOG.md, civis/tests/test_futures.py, civis/tests/test_io.py, civis/tests/test_parallel.py, civis/tests/test_polling.py, civis/tests/test_utils.py
Remove unneeded time.sleep call in test_polling.py.
Remove pytest.mark calls in test_io.py.
=> [CIVIS-1677] TST Optimize tests by removing marks and unneeded sleep calls

CHANGELOG.md, civis/io/_tables.py
Added a data type guardrail in civis.io.civis_file_to_table that raises a type error if file_id is a string.
=> [CIVIS-2263] ENH Add a data type guardrail for `civis.io.civis_file_to_table`

tools/smoke_tests.py
The civis-python smoke tests on Civis Platform run two CivisML training jobs. It's come to my attention that these CivisML jobs have confused our internal product team, since these jobs are incorrectly counted as genuine CivisML usage. This PR explicitly marks these CivisML jobs launched by civis-python smoke tests as unrelated. I've just tested this change and everything worked as expected and desired:
=> [CIVIS-3365] TST mark CivisML smoke test as non-usage related

CHANGELOG.md, civis/base.py, civis/tests/test_base.py, tools/smoke_tests.py
Wrapped response.json() in a try-except to catch JSONDecodeErrors in CivisAPIError.
=> [CIVIS-1972] BUG catch empty API response

.circleci/config.yml, CHANGELOG.md, dev-requirements.txt, requirements.txt, setup.py
This PR turns on CircleCI builds for Python 3.10 and 3.11. We're also dropping Python 3.7.
=> [CIVIS-1767] MAINT support Python 3.10 and 3.11, drop 3.7

.circleci/config.yml, CHANGELOG.md, civis/cli/_cli_commands.py, civis/io/_files.py, civis/io/_tables.py, civis/tests/test_io.py, requirements.txt
Before this pull request, the `main` branch was broken because joblib >= 1.3.0 is incompatible with the current civis-python codebase, thereby making the test suite unable to run at all on CI. This pull request caps joblib to `< 1.3.0` so that the `main` branch is back to a healthy state for CI builds so as to not block other dev work on `main`.
Note that this pull request does not fully address the linked, internal ticket CIVIS-6486 (which has the goal of making civis-python compatible with joblib >= 1.3.0, something we aren't prioritizing at the moment), but is related to it.
Resolves #468.
---
=> [CIVIS-6486] DEP limit `joblib` to `< 1.3.0`

CHANGELOG.md, civis/base.py, civis/civis.py, civis/futures.py, civis/io/_databases.py, civis/io/_files.py, civis/io/_tables.py, civis/parallel.py, civis/polling.py, civis/resources/_resources.py, civis/run_joblib_func.py, civis/service_client.py, civis/tests/test_cli.py, civis/tests/test_deprecate.py, civis/tests/test_futures.py, civis/tests/test_parallel.py, civis/tests/test_resources.py, civis/utils/_jobs.py, docs/source/conf.py
Parameters for various classes/functions that have long been deprecated are removed:
`api_key`, `resources`, `retry_total`, `archive`, `headers`, and the deprecated methods in `ServiceClient`.
=> [CIVIS-5257] RM deprecated parameters and functions

CHANGELOG.md, civis/base.py, civis/civis.py, civis/response.py, civis/service_client.py, civis/tests/test_response.py
It's unclear why one would want to deal with an API response as a pandas object. Since `"pandas"` became an option of the response return type in both this codebase and its internal, private precursor 8+ years ago, it has seen zero internal usage. From users external to Civis, the one time we heard about this usage was when an error was raised (see the linked internal ticket) 4 years ago. All this is to say, it's time to simply drop this  `"pandas"` option to avoid further confusion.
---
=> [CIVIS-2562] RM drop API response return type "pandas"

CHANGELOG.md, civis/civis.py, civis/tests/test_civis.py
This pull request fixes `civis.find` for its unintuitive behavior with boolean kwarg filters. As suggested in #227, boolean kwargs are now treated the same way as kwargs of other data types, for value comparison instead of presence or absence of an attribute.
Resolves #227.
---
=> [CIVIS-5287] FIX `find` should handle boolean kwargs like other data types

.circleci/config.yml, CHANGELOG.md
This pull request adds the `pip-audit` check to CI for potential security vulnerabilities of the Python dependencies that this codebase uses.
---
=> [CIVIS-5100] SEC add `pip-audit` check

CHANGELOG.md, src/civis/futures.py, tests/test_futures.py
Let's do another new feature. Since we often craft the job URL from a `CivisFuture` object for logging etc., this pull request adds the `job_url` property to `CivisFuture`.
---
=> [CIVIS-8512] ENH `job_url` property at `CivisFuture`

.circleci/config.yml, CHANGELOG.md, docs/requirements.txt
The latest CircleCI build at `main` [failed](https://github.com/civisanalytics/civis-python/runs/25198313180) because `requests` had just been updated for a security vulnerability ([ref](https://github.com/civisanalytics/civis-python/security/dependabot/3)). I ran the `pip-compile` command with `--upgrade` to refresh `docs/requirements.txt`.
---
=> [CIVIS-5100] SEC bump `requests` version to 2.32.1 in `docs/requirements.txt`

CHANGELOG.md, docs/source/responses.rst, pyproject.toml, src/civis/cli/__main__.py, src/civis/io/_files.py, src/civis/loggers.py, src/civis/parallel.py, src/civis/response.py, src/civis/tests/mocks.py, src/civis/utils/_jobs.py, tests/test_futures.py, tests/test_loggers.py, tests/test_parallel.py, tests/test_response.py
This pull request updates `civis.response.Response`:
* Fix `.json()` where nested list objects weren't handled correctly.
* Add repr and pretty-printing protocols to improve user experience
Also added `civis --version` and fixed a small bug for `civis_logger` along the way.
---
=> [CIVIS-8660] ENH response objects: add repr and pprint, fix lists for `.json()`

.circleci/config.yml, CHANGELOG.md, docs/requirements.txt, docs/source/conf.py, docs/source/index.rst, docs/source/parallel.rst, pyproject.toml, src/civis/base.py, src/civis/futures.py, src/civis/parallel.py, src/civis/run_joblib_func.py, tests/test_parallel.py
Major changes from joblib v1.2.0 to v1.3.0 are incompatible with civis-python. This issue was first reported in #468, and was temporarily fixed by pinning joblib at < v1.3.0 in #469. This pull request updates civis-python so that now it works with joblib >= v1.3.0. After this pull request is merged, I will not make a new civis-python release yet (I have one or two more pull requests in mind before another release). For this pull request, copying notes from the changelog being updated:
- Refactored the `civis.parallel` module and related unit tests due to major changes
of joblib from v1.2.0 to v1.3.0 (API-breaking changes for dropping
`joblib.my_exceptions.TransportableException` and `joblib.format_stack.format_exc`,
as well as the substantial changes to the internals of …
=> [CIVIS-6486] ENH `civis.parallel` compatible with joblib >= v1.3.0

src/civis/__init__.py, src/civis/_camel_to_snake.py, src/civis/_utils.py, src/civis/ml/_model.py, src/civis/resources/__init__.py, src/civis/resources/_resources.py, src/civis/response.py, src/civis/service_client.py, tests/test_camel_to_snake.py, tests/test_client.py, tests/test_ml/test_model.py, tests/test_resources.py, tests/test_response.py, tests/test_service_client.py, tests/test_utils.py
The startup time when just running `import civis` in a fresh Python interpreter session appears to be long. This is especially noticeable in an interactive environment (the regular Python interactive interpreter, IPython, or a Jupyter notebook), which isn't great for user experience. This pull request applies lazy imports to the top-level `civis.*` modules, for a speed boost of about 5x. The relatively long startup time was due to importing dependencies like pandas through `civis.io` and other pydata packages (numpy, scipy) through `civis.ml`.
We can use `python -X importtime -c 'import civis'` to get the import time details. Before this pull request (for brevity, just showing the final line for the top-level `civis` import):
```
import time: self [us] | cumulative | imported package
... …
```
=> [CIVIS-8658] PERF speed up startup time

CHANGELOG.md, docs/source/user_guide.rst, src/civis/__init__.py, src/civis/base.py, src/civis/futures.py, src/civis/ml/_model.py, src/civis/polling.py, tests/test_polling.py
This pull request makes polling at future objects more efficient, in that a short-running job's `future.result()` should return faster than before.
Before this PR, the default polling interval was a constant of 15 seconds. After this PR, the default polling interval starts at 1 second, increases geometrically for subsequent polls, and is capped at a maximum of 15 seconds. If the user provides a number to the `polling_interval` argument, the polling interval will be a constant of this number (so no change from before this PR).
---
=> [CIVIS-1949] PERF more efficient polling at future objects

CHANGELOG.md, docs/source/cli.rst, docs/source/index.rst, docs/source/responses.rst, docs/source/user_guide.rst, pyproject.toml, src/civis/__init__.py, src/civis/client.pyi, src/civis/io/_tables.py, src/civis/resources/_client_pyi.py, src/civis/resources/_resources.py, src/civis/response.py, tests/test_io.py, tests/test_resources.py, tests/test_response.py
This pull request adds a new feature to the `civis.io.*` functions that call `client.scripts.post_sql` under the hood, for passing in SQL parameters and arguments. This new feature lets the user take advantage of Civis Platform's parameterized SQL scripts with functionality to mitigate security risks of SQL injections. See the linked internal ticket for testing this new feature.
Also going to make a new release of v2.3.0 after this pull request, so I'm bundling in here a few small fixes as well -- they're noted both in the changelog and comments on this PR.
---
=> [CIVIS-8695] ENH SQL I/O functions accept SQL parameters and arguments

CHANGELOG.md, src/civis/cli/_cli_commands.py, tests/test_cli.py
In #498, I added support for `description` in the `civis.io.*` functions that upload to a Civis file, but forgot to handle the file upload command in the command-line interface. This pull request addresses this.
---
=> [CIVIS-9155] ENH support `description` in file upload CLI

CHANGELOG.md, MANIFEST.in, pyproject.toml
This pull request bumps version to v2.4.0 for a new release!
---
=> [CIVIS-9806] MAINT bump version to v2.4.0

CHANGELOG.md, src/civis/resources/_api_spec.py
This pull request fixes a bug in the script for checking whether the Civis API spec has been updated. For background, the script works by comparing the function signatures for all the `client.<endpoint>.<method>` methods between the versioned `civis_api_spec.json` and the live spec pulled from the upstream Civis API. Before this PR, the comparison was the equality test between `inspect.signature(method1)` and `inspect.signature(method2)`, which included the equality comparison of their return annotations. Since #501, these return annotations are dynamically generated classes (which has response attributes and their types, and has the class name beginning with `_Response`). What I missed was that even if two dynamically generated classes are defined identically, comparing them for equality …
=> [CIVIS-9898] MAINT fix script for checking API spec changes

CHANGELOG.md, docs/utils.rst, pyproject.toml, src/civis/cli/_cli_commands.py, src/civis/utils/__init__.py, src/civis/utils/_jobs.py, tests/test_jobs.py
This does two things:
* Adds `civis.utils.job_logs()` function to return a generator of log messages for a job run
* Revises the CLI commands `civis jobs follow-log` and `civis jobs follow-run-log` to not skip log messages for running jobs
---
=> [CIVIS-10251] Add `civis.utils.job_logs()` function

CHANGELOG.md, docs/requirements.txt, src/civis/utils/_jobs.py
This adds some examples to the `job_logs` function added in #509.
It also updates the requirements due to GHSA-cpwx-vrp4-4pq7.
---
- N/A If applicable, unit tests have been added and/or updated
=> [CIVIS-10251] Add examples to `civis.utils.job_logs` docstring

CHANGELOG.md, docs/requirements.txt, pyproject.toml, src/civis/parallel.py
When I worked on #512, I noticed that the test suite threw a joblib deprecation warning:
```
.../site-packages/joblib/_parallel_backends.py:122: DeprecationWarning: `apply_async` is deprecated, implement and use `submit` instead.
```
Since [joblib v1.5.0 released in May 2025](https://github.com/joblib/joblib/blob/0672e76ad10e9f463221a58fb7bffa127287a4ba/CHANGES.rst?plain=1#L61-L62), joblib's `ParallelBackendBase` has been refactored [with the effect of favoring `submit` over `apply_async`](https://github.com/joblib/joblib/blob/0672e76ad10e9f463221a58fb7bffa127287a4ba/joblib/_parallel_backends.py#L89-L126). To be more forward-compatible, this pull request updates civis-python's parallel backend, which subclasses joblib's `ParallelBackendBase`. After this PR, joblib's deprecation warning no …
=> [CIVIS-10982] ENH update Civis parallel backend internals for refactored joblib backend

CHANGELOG.md, pyproject.toml, src/civis/client.pyi, src/civis/resources/_client_pyi.py
In #521, I forgot to add the new kwarg `user_agent` for `civis.APIClient` in the stub file `client.pyi`. This PR fixes this issue.
---
=> [CIVIS-11076] FIX add kwarg `user_agent` in `civis.APIClient` in stub file
