civis/io/_tables.py
Resolves #6.  This should be slightly faster since we'll be reading directly from memory rather than from disk.
=> Avoiding roundtrip to disk in read_civis_sql

civis/io/_tables.py
Use an in-memory stream instead of writing to a temporary file.
=> Do not write to disk in dataframe_to_civis

CHANGELOG.md
Will release 1.1.0 upon merge.
=> updating changelog in anticipation of 1.1.0

CHANGELOG.md, civis/polling.py
The `_poller` and `_polling_args` attributes of `PollableResult` might be generally useful when building custom workflows. This PR exposes these attributes as public to designate them as safe to access.
=> Updates to polling

civis/io/_files.py
Adding a quick example to showcase how to upload files both temporarily and permanently.
=> [CIVP-10078] Adding examples for file_to_civis

civis/cli/__main__.py
=> BUG make sure click fails properly

CHANGELOG.md, civis/io/_tables.py
No functional changes. This will be required to take advantage of changes to platform exports.
=> Add CSV settings options to civis.io module

civis/futures.py
This should be the correct API from Pubnub as per https://www.pubnub.com/docs/python/api-reference
=> [CIVP-10738] Fixed pubnub reconnect policy

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
Add the `ModelPipeline` class, the primary abstraction for creating and running modeling jobs in the Civis Platform.
=> [CIVP-10806] Add ModelPipeline class

CHANGELOG.md, civis/io/_files.py
as this is what iter_content() provides in the function
=> Revised example to pass bytes

civis/io/_files.py, docs/source/conf.py, docs/source/io.rst
This adds the new functions to the sphinx documentation.  It also has some small fixes to address warnings sphinx was raising.
=> Add missing io docs

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
Example email: ![image](https://cloud.githubusercontent.com/assets/7613058/26794143/30453ce4-49e6-11e7-81e6-cf75b8c6a5bd.png)
=> [PARO-307] ModelPipeline email notifications

CHANGELOG.md, examples/CivisML_parallel_training.ipynb
Null values should be retained in the data transformation (although irrelevant here, in other datasets this can be important and will allow people to more readily follow the example).
The parenthesis around the second condition are unnecessary but IMO provide clarity.
=> Ensuring null values are preserved in data transformation.

CHANGELOG.md, examples/PythonAPIClientDemo.ipynb
This notebook demonstrates the use of all the abstractions and patterns used in the Python API client. It serves as an introduction to the Python API client for technical users of Civis Platform.
=> DOC Add API client example notebook

CHANGELOG.md, civis/compat.py
This PR adds a ResourceWarning for python 2.7
=> [CIVP-12455] BUG add a ResourceWarning for python 2.7

examples/PythonAPIClientDemo.ipynb
Reduce clutter in the list of tables; focus on the ones relevent for the demo rather than filling the screen with the full list.
=> DOC Modify table list in API client demo notebook

CHANGELOG.md
Update changelog for multiindex dataframe error handling.
=> [PARO-436] DOC update changelog for PR #131

docs/source/ml.rst
@jmemich Mind taking a look at this?
=> DOC: Fix markup

CHANGELOG.md, civis/cli/__main__.py, civis/cli/_cli_commands.py
This makes it easier to download a notebook to a local file.
=> added "civis notebooks download" CLI command

CHANGELOG.md, civis/io/_tables.py
This PR adds this new parameter to the IO functions. It should also be added to advanced options in the post_syncs endpoint, but that's autogenerated.
Looking at the existing test coverage here, it looks like we don't typically have tests for each specific parameter, but let me know if I should add some for this.
=> [CIVP-13581] add diststyle param to IO functions

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
Also modify the template fallback logic such that users get the most recent template to which they have access, in case there's more than one such template.
=> ENH Increase max CivisML template to v2.1

CHANGELOG.md, tools/smoke_tests.py
This adds a script for running some simple tests that hit the live Civis platform.
=> Add script for smoke tests

CHANGELOG.md, civis/civis.py, dev-requirements.txt
=> DOC Document civis.find and civis.find_one

README.rst
This adds some basic badges to the readme.
=> add some basic badges to the readme

CHANGELOG.md, civis/civis.py, civis/tests/test_civis.py
=> FIX get_table_id should correctly handle quoted schema.tablename

CHANGELOG.md, docs/source/io.rst
Looks like these functions didn't make it into the docs.
=> DOC: Adding missing docs to sphinx

CHANGELOG.md
Forgot to update the changelog for PR #343, changes made for SERD-1694.
=> DOC updating changelog

CHANGELOG.md, civis/ml/_model.py, civis/ml/tests/test_model.py
@jacksonllee take a look at what I found and let me know if this makes sense.
=> bug with from_existing

.travis.yml, CHANGELOG.md, README.rst, civis/base.py, civis/polling.py, setup.py
=> fix futures for python 3.8 and enable python 3.8 builds

civis/io/_tables.py
[APIC-304](https://civisanalytics.atlassian.net/browse/APIC-304)
=> [APIC-304] Update descriptions for table_columns attribute

CHANGELOG.md, civis/_utils.py, civis/civis.py, civis/tests/test_utils.py
=> [CIVP-22369] - bug fix retry on iterate

CHANGELOG.md, civis/io/_tables.py
This PR is a follow-up of #430, where I missed the `assert` statements in `_tables.py` somehow.
=> [CIVIS-1609] FIX remove more `assert` statements

.gitignore, CHANGELOG.md, docs/source/user_guide.rst
This PR is for adding documentation for best practices when testing, in reference to [JIRA ticket 1630](https://civisanalytics.atlassian.net/browse/CIVIS-1630). I used an internal civis function and the python mocking library in line with best practices. 
Thanks for the review, and please let me know if you see anything that you'd like done differently!
Thanks Jackson!
Closes #306
=> [CIVIS-1630] DOC document best practices for testing

CHANGELOG.md, docs/source/user_guide.rst
=> [CIVIS-3888] Update civis-python user guide to correct initiation of civis.APIClient() object

CHANGELOG.md, docs/source/user_guide.rst, src/civis/__init__.py, src/civis/workflows/__init__.py, src/civis/workflows/_schema.py, src/civis/workflows/_schemas.py, src/civis/workflows/_validate.py, tests/test_workflows/test_validate.py
This pull request adds the function `civis.workflows.validate_workflow_yaml` to validate a Civis Platform workflow YAML definition.
---
=> [CIVIS-8846] ENH validate a workflow YAML definition

CHANGELOG.md, pyproject.toml, src/civis/__init__.py, src/civis/base.py, src/civis/cli/__main__.py, src/civis/client.py, src/civis/resources/_resources.py, tests/test_resources.py
This pull request adds a new `user_agent` kwarg to `civis.APIClient`.
---
=> [CIVIS-11076] ENH add `user_agent` kwarg to `civis.APIClient`
